### ISSUE TITLE
Clear edits

### ISSUE THREAD

**Issue by dalekunce** [AmericanRedCross/OpenMapKit#38]
Need a way to clear accidental edits of a feature.

Users sometimes click on and complete form for wrong feature. Need the ability to click on a feature and clear all the changes.

**Comment by hallahan** [comment]
Adding a Cancel button via #15

**Comment by hallahan** [comment]
I'm thinking this should actually happen in ODK Collect. I think it will make sense to but a button in there since that is where you see the file name of the edited OSMWay.xml. There would be a button to simply delete that file, which is the edit, and then you can launch back into OpenMapKit to select a new feature.

**Comment by hallahan** [comment]
Turns out it keeps writing more OSM Files to the ODK directory. Need to fix this.

![screenshot 2015-04-07 12 10 46](https://cloud.githubusercontent.com/assets/556367/7031293/3ffaa43e-dd1f-11e4-9ff8-790a6cb4b607.png)

**Comment by hallahan** [comment]
The button now shows this, and when you redo your tag, saving will delete the old file. Need to implement that logic in OpenMapKit.

![asdfasdf](https://cloud.githubusercontent.com/assets/556367/7031681/22464d96-dd22-11e4-84f7-6d5065fcd88b.png)

**Comment by hallahan** [comment]
Ok, done.
